/**
 * Build-time reader for the BOSC content bundle (Epic #53 — the data tier).
 *
 * The bundle is a directory of typed JSON feeds indexed by a `manifest.json`
 * (see `data/site/bundle/README.md`). Bundles are **per network site** (#724/#727):
 * each call resolves a site's bundle by registry slug (default `lima`), so the
 * network's sites read independent data in one build. This module pulls feeds off
 * disk at build time — Astro page frontmatter runs in Node during `astro build`, so
 * plain `node:fs` is the right tool, not `fetch`.
 *
 * Per-site resolution order for a slug (first with a `manifest.json` wins):
 *   1. $WATERMARK_BUNDLE_DIR/<slug>     — explicit override, per-site subdir
 *   2. $WATERMARK_BUNDLE_DIR            — explicit override as a single bundle (back-compat)
 *   3. ../data/site/bundles/<slug> — the real per-site bundle, generated by the Vite plugin
 *   4. ../data/site/bundle         — legacy single-site path (Lima only; pre-#727 parity)
 *
 * The feeds under (3)/(4) are git-ignored. The watermarkBundle Vite plugin runs
 * `watermark --site <slug> export` in buildStart so they exist before Astro reads them.
 * For the offline `//web:check` gate, set WATERMARK_BUNDLE_DIR=sites — the
 * committed fixtures are an explicit opt-in, not a silent fallback.
 */
import { AsyncLocalStorage } from "node:async_hooks";
import { existsSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { cwd, env } from "node:process";
import { fileURLToPath } from "node:url";
import type { HypothesisItem } from "./feeds";
import { LIMA_SLUG } from "./routes";

const HERE = dirname(fileURLToPath(import.meta.url));
// `web/` (the Astro frontend root) — the anchor for the committed-bundle fallback paths below
// (`FRONTEND_ROOT/../data/...`). Since Epic #1549 this module lives at web/packages/core/src, so
// we can't count a fixed number of `..`; walk up to the directory that holds astro.config.ts.
// That's robust to the extra nesting AND to the pnpm symlink layout (web/node_modules/@watermark/
// core → …/packages/core). Only ever evaluated in Node/build contexts — the Workers-runtime
// function closure never imports bundle.ts, so `existsSync` here is safe.
function findFrontendRoot(start: string): string {
  let dir = start;
  for (let i = 0; i < 8 && dir !== dirname(dir); i++) {
    if (existsSync(join(dir, "astro.config.ts"))) return dir;
    dir = dirname(dir);
  }
  return resolve(start, "..", "..", ".."); // fallback: web/packages/core/src → web/
}
const FRONTEND_ROOT = findFrontendRoot(HERE);

/**
 * The active network site (#724/#739) — an ambient context so every `loadFeed`/`hasFeed` reads
 * the right site's bundle without threading a slug through the ~12 feed libs and ~40 pages. The
 * middleware (`src/middleware.ts`) resolves the slug from the request path and wraps the page
 * render in `runWithSite`; build-time reads inside that render pick it up. This module is
 * build-only (it already uses `node:fs`), so `AsyncLocalStorage` is safe here — it never reaches
 * a client bundle. Outside a render (global pages, getStaticPaths planning) the store is empty
 * and the active site defaults to Lima.
 */
const siteStore = new AsyncLocalStorage<string>();

/** Run `fn` with `slug` as the active site for any bundle reads it (transitively) performs. */
export function runWithSite<T>(slug: string, fn: () => T): T {
  return siteStore.run(slug, fn);
}

/** The active site's registry slug, or `lima` outside a `runWithSite` scope. */
export function activeSite(): string {
  return siteStore.getStore() ?? LIMA_SLUG;
}

/** A feed's storage shape, mirroring `bosc.site.feeds.FeedKind`. */
export type FeedKind = "collection" | "object" | "geojson";

/** One feed's entry in the manifest index (`bosc.site.feeds.FeedRef`). */
export interface FeedRef {
  name: string;
  path: string;
  media_type: string;
  schema: string;
  kind: FeedKind;
  count: number;
}

/** A downloadable graph export's format (`bosc.site.feeds.ExportFormat`). */
export type ExportFormat = "turtle" | "jsonld" | "graphml";

/** One graph export's entry in the manifest's `exports` index (`bosc.site.feeds.ExportRef`, #1574) —
 *  an RDF/GraphML serialization of the corpus mirror, downloadable from the wiki graph page. */
export interface ExportRef {
  name: string;
  path: string;
  media_type: string;
  format: ExportFormat;
  node_count: number;
  edge_count: number;
}

/** A domain's activation state (`bosc.site.readiness.State`). */
export type DomainState = "absent" | "seeded" | "live";
/** A site's readiness tier (`bosc.site.readiness.Tier`). */
export type SiteTier = "stub" | "backdrop" | "case" | "reference";

/** The standing domain-activation readiness (`bosc.site.feeds.SiteReadiness`, #1220) — the five
 *  domains' states plus the derived tier, recomputed at every export. The frontend reads this
 *  instead of re-deriving section gating from raw feed counts (`readiness.ts`). */
export interface Readiness {
  tier: SiteTier;
  domains: {
    backdrop: DomainState;
    facility: DomainState;
    places: DomainState;
    record: DomainState;
    story: DomainState;
  };
}

/** The bundle index (`bosc.site.feeds.Manifest`). Read this first. */
export interface Manifest {
  /** The network-site slug this bundle is for (#762) — so a bundle self-identifies. */
  site: string;
  bundle_version: string;
  contract_version: string;
  generated_at: string;
  feed_count: number;
  row_total: number;
  /** Standing domain-activation readiness (#1220 / contract 1.17.0). Optional only so a
   *  synthetic/pre-1.17 fixture without the block degrades (all-absent) rather than crashing. */
  readiness?: Readiness;
  feeds: FeedRef[];
  /** Downloadable graph exports of the corpus mirror (#1574 / contract 1.28.0). Optional: absent
   *  from a redirected/test bundle or a pre-1.28 fixture, so the graph page degrades to no downloads. */
  exports?: ExportRef[];
}

function candidateDirs(slug: string): string[] {
  const dirs: string[] = [];
  const override = env.WATERMARK_BUNDLE_DIR;
  if (override) {
    const root = isAbsolute(override) ? override : resolve(cwd(), override);
    // Prefer a per-site subdir of the override; fall back to it as a single bundle.
    dirs.push(join(root, slug), root);
  }
  dirs.push(resolve(FRONTEND_ROOT, "..", "data", "site", "bundles", slug));
  // The pre-#727 single-site path, kept as a Lima-only fallback so an existing local
  // bundle keeps rendering until it's re-exported to the per-site path.
  if (slug === LIMA_SLUG) dirs.push(resolve(FRONTEND_ROOT, "..", "data", "site", "bundle"));
  return dirs;
}

const cachedDirs = new Map<string, string>();

/** The resolved bundle root for a site — the first candidate that holds a `manifest.json`. */
export function bundleDir(slug: string = activeSite()): string {
  const cached = cachedDirs.get(slug);
  if (cached) return cached;
  for (const dir of candidateDirs(slug)) {
    if (existsSync(join(dir, "manifest.json"))) {
      cachedDirs.set(slug, dir);
      return dir;
    }
  }
  throw new Error(
    `No content bundle found for site "${slug}". Run \`npm run build\` (plugin exports ` +
      `automatically) or set WATERMARK_BUNDLE_DIR=sites to use the committed ` +
      `fixtures. Looked in:\n  ${candidateDirs(slug).join("\n  ")}`,
  );
}

const cachedManifests = new Map<string, Manifest>();

/**
 * The bundle `contract_version` major this frontend is built against. A bundle
 * with a different major has breaking schema changes (the `CONTRACT_VERSION`
 * major in `bosc.site.feeds`), so we fail the build fast with a clear message
 * rather than render against an incompatible shape. Bump when adapting the
 * frontend to a new contract major.
 */
export const EXPECTED_CONTRACT_MAJOR = 1;

/** Parse and return a site's bundle manifest (cached per slug for the build). */
export function loadManifest(slug: string = activeSite()): Manifest {
  const cached = cachedManifests.get(slug);
  if (cached) return cached;
  const raw = readFileSync(join(bundleDir(slug), "manifest.json"), "utf-8");
  const manifest = JSON.parse(raw) as Manifest;
  const major = Number.parseInt(String(manifest.contract_version).split(".")[0], 10);
  if (!Number.isFinite(major) || major !== EXPECTED_CONTRACT_MAJOR) {
    throw new Error(
      `Bundle contract_version "${manifest.contract_version}" (site "${slug}") is incompatible ` +
        `with this frontend (expected major ${EXPECTED_CONTRACT_MAJOR}). Regenerate with a ` +
        `matching \`bosc export\`, or bump EXPECTED_CONTRACT_MAJOR in src/lib/bundle.ts.`,
    );
  }
  cachedManifests.set(slug, manifest);
  return manifest;
}

/** Whether a site's bundle exposes a feed by this name. Section pages and the search
 * index guard on this because the committed committed site bundle ships a subset. */
export function hasFeed(name: string, slug: string = activeSite()): boolean {
  return loadManifest(slug).feeds.some((f) => f.name === name);
}

function feedRef(name: string, slug: string): FeedRef {
  const manifest = loadManifest(slug);
  const ref = manifest.feeds.find((f) => f.name === name);
  if (!ref) {
    const known = manifest.feeds.map((f) => f.name).join(", ");
    throw new Error(`Feed "${name}" is not in the "${slug}" bundle manifest. Available: ${known}`);
  }
  return ref;
}

/**
 * Read one feed by manifest name from a site's bundle. `collection`/`geojson` feeds
 * return the parsed array or FeatureCollection; `object` feeds return the single object.
 * NDJSON collections (large feeds, one row per line) are parsed line-by-line. The shape
 * is the caller's responsibility — pass the matching feed type as `T`.
 */
export function loadFeed<T = unknown>(name: string, slug: string = activeSite()): T {
  const ref = feedRef(name, slug);
  const raw = readFileSync(join(bundleDir(slug), ref.path), "utf-8");
  if (ref.path.endsWith(".ndjson")) {
    const rows = raw
      .split("\n")
      .filter((line) => line.trim().length > 0)
      .map((line) => JSON.parse(line));
    return rows as T;
  }
  return JSON.parse(raw) as T;
}

/** The downloadable graph exports a site's bundle advertises (#1574), or [] when the bundle
 *  carries none (a redirected/test export, a thin peer, or a pre-1.28 fixture). The wiki graph
 *  page reads this to render the download links and degrades cleanly to none. */
export function getExports(slug: string = activeSite()): ExportRef[] {
  return loadManifest(slug).exports ?? [];
}

/**
 * Read a raw (non-JSON) bundle artifact — a graph export's `.ttl`/`.jsonld`/`.graphml` payload
 * (#1574) — as text, by its bundle-root-relative `path`. The `/exports/[file]` endpoints serve
 * these verbatim with the export's own media type; unlike `loadFeed` it never JSON-parses.
 */
export function readBundleText(path: string, slug: string = activeSite()): string {
  return readFileSync(join(bundleDir(slug), path), "utf-8");
}

/** Convenience wrapper — the three-hypothesis feed, or [] if unavailable. */
export function getHypotheses(): HypothesisItem[] {
  return hasFeed("hypotheses") ? loadFeed<HypothesisItem[]>("hypotheses") : [];
}
