"""The federal-enclave model — a base's own land, water, wastewater, power and toxics (#1664).

Epic #1659 ME-E. Before this module a federal installation appeared in the platform only as
*county backdrop*: WPAFB carried no facility, no parcel geometry, and no toxics row of its own,
while running 17 supply wells over a sole-source aquifer, discharging under two NPDES permits, and
sitting on the National Priorities List with ≥58 waste-disposal sites. Three structural blind
spots produced that, and this module closes each by **naming an instrument**, never by estimating:

1. **The facility model was data-center-shaped.** ``SiteFacility.kind = federal_installation``
   (:mod:`watermark.sites`) now carries an enclave, with the data-center dimensions forbidden at
   the type level so no IT load, genset fleet or cooling bracket can be fabricated for a base.
2. **The land model was county-CAMA-shaped.** A federal enclave is off the tax rolls, so its
   ~8,200 acres appear in no county parcel layer, ever. The DoD **MIRTA** site register carries
   the boundary instead (:mod:`watermark.connectors.federal`), and it is committed as its own
   ``federal-land.geojson`` rather than dressed up as a parcel assemblage.
3. **The toxics model was single-county-scoped.** An installation straddling two counties reports
   TRI from the one it is *addressed* in — for WPAFB, **Greene (39057)**, while the site profile's
   economic/RSEI unit is deliberately **Montgomery (39113)** (the well-field / plume / Dayton-metro
   context). So the base was not missing from RSEI; it was out of scope by construction. The
   reconciliation is a second, one-facility reduction against the enclave's own county — plus the
   plain statement that even that row cannot see the CERCLA mass, because RSEI tracks TRI
   reporters and a 1940s-70s base landfill is not a TRI release.

The committed artifact is one small YAML per enclave site (``data/reference/<slug>/enclave.yaml``,
regenerated by ``watermark enclave``). Every documented figure in it is **projected from the
grounding record** (``FederalInstallation.record_relpath`` — WPAFB's CERCLA §120 agreement) or
carried verbatim from a named federal register. Nothing here is estimated, and a figure the
sources do not carry is ``None`` (``[open]``) rather than defaulted.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml
from pydantic import BaseModel, ConfigDict

from watermark.config import Settings, get_settings
from watermark.connectors.federal import (
    Discharge,
    InstallationBoundary,
    WaterSystem,
    boundary_geojson,
    fetch_discharges,
    fetch_installation_boundary,
    fetch_water_systems,
    write_boundary,
)
from watermark.logging import get_logger
from watermark.models import OptApproxInt
from watermark.rsei import RseiFacility, build_inventory, write_inventory
from watermark.sites import FederalInstallation, SiteProfile, active_profile

if TYPE_CHECKING:
    from watermark.rsei import RseiInventory

log = get_logger(__name__)

# The RSEI caveat that matters most for an enclave, spelled out where the enclave's own row is
# published so it can never be read as the base's total contaminant mass.
RSEI_CERCLA_GAP = (
    "RSEI tracks TRI **reporting** — annual releases from a covered facility. It does not, and "
    "cannot, carry the CERCLA mass: legacy waste-disposal sites, landfills, fire-training areas "
    "and the resulting groundwater plume predate TRI (reporting began in 1987) and are not "
    "releases under it. The enclave's Superfund record is the instrument for that, and the two "
    "are complements, not alternatives — neither is the base's total contaminant footprint."
)


class EnclaveRecordFacts(BaseModel):
    """The enclave facts read out of the grounding record (``installation.record_relpath``).

    The **projection seam**: rather than re-keying a primary instrument's numbers into a profile
    literal (where they would drift from the record silently), the record is read and these
    optional fields are lifted from it. Every field is optional — a different enclave's grounding
    record will document a different subset, and a missing field is ``[open]``, not zero.

    The key names are the ones an enclave-grounding extraction uses at its top level, alongside
    the standard ``action`` block (see ``data/extracted/wpafb/cercla-ffa-1991.epa.yaml``). Values
    may carry the repo's approximate marker (``~8200``); ``OptApproxInt`` preserves that reading
    rather than dropping it (see :mod:`watermark.models`).
    """

    model_config = ConfigDict(extra="ignore", frozen=True)

    base_area_acres: OptApproxInt = None
    supply_wells: OptApproxInt = None
    well_fields: OptApproxInt = None
    air_stripping_units: OptApproxInt = None
    aquifer: str | None = None
    waste_disposal_sites: OptApproxInt = None
    contaminants_vocs: tuple[str, ...] = ()
    disposal_period: str | None = None
    npl_listing_date: str | None = None
    npl_citation: str | None = None
    epa_superfund_site_id: str | None = None
    statutory_authority: str | None = None


# A register/record acreage gap wider than this is reported as a coverage caveat rather than
# left for a reader to notice. It is a REPORTING threshold, not a correction: neither figure is
# adjusted toward the other, and the boundary is never rescaled to match the record.
_ACREAGE_TOLERANCE_PCT = 5.0


class EnclaveLand(BaseModel):
    """The enclave's land: the federal register's boundary, cross-checked against the record."""

    model_config = ConfigDict(extra="forbid")

    register_name: str
    feature_name: str
    site_name: str
    operational_status: str
    is_joint_base: bool
    # Measured from the committed boundary geometry in the site's own UTM zone.
    register_acres: float
    parts: int = 1  # disjoint parts the register draws the site in
    # The acreage the grounding record states, when it states one. Kept ALONGSIDE rather than
    # reconciled away: they are independent measurements from different instruments and vintages
    # (WPAFB's 1991 agreement says "approximately 8,200 acres" across Areas A/C and B; the 2015
    # BSR-derived register polygon measures ~5,230), and picking one would discard a disagreement
    # a reader is entitled to see.
    record_acres: int | None = None
    # (register - record) / record, as a percentage. Negative ⇒ the register draws LESS land than
    # the record describes, which is the coverage direction that matters: it means the boundary
    # understates the enclave, so it must not be used as the enclave's extent.
    acreage_delta_pct: float | None = None
    acreage_note: str | None = None
    relpath: str  # the committed federal-land.geojson, relative to data_dir
    note: str = (
        "A federal enclave is off the county tax rolls and appears in no county CAMA parcel "
        "layer. This boundary is the DoD's own site register — federally owned or otherwise "
        "managed land, planning-grade, not a legal survey."
    )


def _acreage_reconciliation(
    register_acres: float, record_acres: int | None, *, parts: int
) -> tuple[float | None, str | None]:
    """Compare the register's measured acreage against the record's stated acreage.

    Returns ``(delta_pct, note)``. Neither figure is adjusted — the note names the disagreement
    and says which instrument governs the enclave's extent, because a boundary that draws only
    part of a base would otherwise silently become "the base" on a map.
    """
    if record_acres is None or record_acres <= 0:
        return None, None
    delta = round(100.0 * (register_acres - record_acres) / record_acres, 1)
    if abs(delta) <= _ACREAGE_TOLERANCE_PCT:
        return delta, None
    direction = "less" if delta < 0 else "more"
    return delta, (
        f"COVERAGE CAVEAT: the register's polygon measures {register_acres:,.0f} acres — "
        f"{abs(delta):g}% {direction} than the {record_acres:,} acres the grounding record "
        f"states, across {parts} mapped part(s). The two are not reconciled here and neither is "
        f"adjusted toward the other: the record is the instrument for the enclave's EXTENT, the "
        f"register only for where mapped land sits. Treat the boundary as a partial footprint, "
        f"not the installation's area."
    )


class EnclaveWater(BaseModel):
    """The enclave's own water supply — its public water systems plus the record's wellfield."""

    model_config = ConfigDict(extra="forbid")

    systems: list[WaterSystem] = []
    population_served: int | None = None  # summed across the enclave's own systems
    service_connections: int | None = None
    # From the grounding record (the CERCLA Findings of Fact for WPAFB).
    supply_wells: int | None = None
    well_fields: int | None = None
    treatment_units: int | None = None
    aquifer: str | None = None
    # [open] unless an instrument discloses it. A base is a large water user; that is exactly why
    # no withdrawal may be inferred from population served — this is a supply system, not a meter.
    withdrawal_mgd: float | None = None
    withdrawal_citation: str | None = None


class EnclaveWastewater(BaseModel):
    """The enclave's own permitted discharges (EPA ECHO)."""

    model_config = ConfigDict(extra="forbid")

    discharges: list[Discharge] = []
    # The sum of the reported average flows ECHO carries. A permit ECHO leaves blank contributes
    # nothing and is NOT imputed, so this is a floor on the enclave's effluent, not a total.
    reported_average_flow_mgd: float | None = None
    reported_flow_note: str = (
        "Sum of the reported average flows EPA ECHO carries for the enclave's own permits. A "
        "permit ECHO leaves blank is omitted, never imputed — so this is a floor, not a total."
    )


class EnclavePower(BaseModel):
    """The enclave's electrical load — ``[open]`` unless an instrument discloses it.

    Modeled explicitly rather than omitted, because the absence is the finding: a ~27,000-person
    installation is unmistakably a large load, and the honest representation of that is a named
    gap with the backdrop that does apply, not a plausible number.
    """

    model_config = ConfigDict(extra="forbid")

    load_mw: float | None = None
    load_citation: str | None = None
    note: str = (
        "No instrument in the corpus discloses it, and none may be inferred from acreage or "
        "population. The site's grid backdrop (serving utility, balancing authority, state "
        "denominators) still applies and is carried with load_share null — the enclave is a real "
        "load the grid layer refuses to size."
    )


class EnclaveToxics(BaseModel):
    """The enclave's own contaminant record, and the county scope that structurally misses it."""

    model_config = ConfigDict(extra="forbid")

    # --- TRI / RSEI: the enclave's own row, from its OWN county ---
    tri_facility_id: str | None = None
    tri_county_fips: str | None = None
    tri_county_name: str | None = None
    epa_registry_id: str | None = None
    rsei: RseiFacility | None = None
    rsei_relpath: str | None = None  # the committed one-facility reduction
    # --- The severance this module exists to state ---
    site_rsei_fips: str  # the county the SITE's backdrop inventory covers
    site_rsei_county_name: str
    scope_disagreement: bool  # tri_county_fips != site_rsei_fips
    scope_note: str
    cercla_gap_note: str = RSEI_CERCLA_GAP
    # --- CERCLA / NPL, projected from the grounding record ---
    npl_site_id: str | None = None
    npl_listed_on: str | None = None
    npl_citation: str | None = None
    waste_disposal_sites: int | None = None
    disposal_period: str | None = None
    contaminants: list[str] = []
    statutory_authority: str | None = None


class EnclaveProfile(BaseModel):
    """The committed per-site federal-enclave artifact (``data/reference/<slug>/enclave.yaml``)."""

    model_config = ConfigDict(extra="forbid")

    meta: dict[str, Any]
    slug: str
    name: str
    component: str
    agency: str
    status: str  # the facility lifecycle stage
    record_relpath: str
    land: EnclaveLand | None = None
    water: EnclaveWater
    wastewater: EnclaveWastewater
    power: EnclavePower
    toxics: EnclaveToxics
    citations: list[str] = []


# --- Reads ------------------------------------------------------------------------------


def installation_of(profile: SiteProfile) -> FederalInstallation | None:
    """The active site's federal installation, or ``None`` when it has no enclave facility."""
    fac = profile.facility
    return None if fac is None else fac.installation


def read_record_facts(inst: FederalInstallation, *, settings: Settings) -> EnclaveRecordFacts:
    """Project the enclave facts out of the grounding record (never re-keyed into a profile).

    Raises ``FileNotFoundError`` when the record is missing: the installation declares that path
    as its instrument grounding, so a silently-empty projection would quietly downgrade a
    [verified] enclave to a name.
    """
    path = settings.extracted_dir / inst.record_relpath
    if not path.is_file():
        raise FileNotFoundError(
            f"federal-installation record not found: {path} (FederalInstallation.record_relpath="
            f"{inst.record_relpath!r}) — the enclave's water/toxics facts are projected from it"
        )
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return EnclaveRecordFacts.model_validate(data)


def enclave_path(settings: Settings) -> Path:
    """The active site's committed enclave artifact path."""
    return settings.reference_dir / settings.site / "enclave.yaml"


def load_enclave(settings: Settings | None = None) -> EnclaveProfile | None:
    """The committed enclave profile for the active site, or ``None`` when it has none."""
    settings = settings or get_settings()
    path = enclave_path(settings)
    if not path.is_file():
        return None
    return EnclaveProfile.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")) or {})


def load_enclave_rsei(settings: Settings | None = None) -> RseiInventory | None:
    """The committed one-facility enclave RSEI reduction, or ``None`` when the site has none."""
    from watermark.rsei import RseiInventory as _Inv

    settings = settings or get_settings()
    relpath = active_profile(settings).enclave_rsei_relpath
    if relpath is None:
        return None
    path = settings.data_dir / relpath
    if not path.is_file():
        return None
    return _Inv.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")) or {})


# --- Build ------------------------------------------------------------------------------


def build_enclave_rsei(settings: Settings | None = None) -> RseiInventory | None:
    """Reduce RSEI to the enclave's OWN facility, in the enclave's OWN reporting county.

    ``None`` when the site has no enclave or the enclave's TRI identity is ``[open]``. The county
    filter is the enclave's ``tri_county_fips`` — deliberately not the site's ``rsei_fips``, and
    deliberately not a widened multi-county scope: widening the county inventory would change what
    the backdrop *means* (and, for WPAFB, silently re-base an economic unit #1660 regenerated).
    """
    settings = settings or get_settings()
    inst = installation_of(active_profile(settings))
    if inst is None or inst.tri_facility_id is None:
        return None
    assert inst.tri_county_fips is not None  # the model pairs the TRI identity all-or-nothing
    assert inst.tri_county_name is not None
    return build_inventory(
        settings,
        fips=inst.tri_county_fips,
        county_name=inst.tri_county_name,
        facility_ids=[inst.tri_facility_id],
    )


def _sum_opt(values: list[int | None]) -> int | None:
    """Total across the enclave's water systems — ``None`` unless **every** system reports.

    All-or-nothing on purpose. Summing only the systems that happen to report would publish a
    partial figure under a total's label ("serving 27,585 people"), which understates by exactly
    the amount nobody can see — the failure mode this repo refuses. A missing system makes the
    total ``[open]``; the per-system rows are still carried, so nothing is lost, and a reader adds
    them up knowing what is absent. (Contrast the wastewater flow, where a partial sum IS reported
    — but explicitly labelled a floor, never a total.)
    """
    if not values or any(v is None for v in values):
        return None
    return sum(v for v in values if v is not None)


def build_enclave(
    settings: Settings | None = None,
    *,
    boundary: InstallationBoundary | None = None,
    systems: list[WaterSystem] | None = None,
    discharges: list[Discharge] | None = None,
    rsei_row: RseiFacility | None = None,
) -> EnclaveProfile | None:
    """Assemble the active site's enclave profile from its record + the federal registers.

    ``None`` for a site with no ``federal_installation`` facility. The four connector results may
    be passed in (the CLI fetches them once and reuses them for the committed boundary/RSEI files);
    omitted, the registers are consulted through the standard cache/offline path.
    """
    settings = settings or get_settings()
    profile = active_profile(settings)
    fac = profile.facility
    inst = installation_of(profile)
    if fac is None or inst is None:
        return None
    facts = read_record_facts(inst, settings=settings)

    if boundary is None and inst.register_name is not None:
        boundary = fetch_installation_boundary(
            inst.register_name, utm_epsg=profile.hydro_utm_epsg, settings=settings
        )
    if systems is None:
        systems = fetch_water_systems(inst.pwsids, settings=settings) if inst.pwsids else []
    if discharges is None:
        discharges = (
            fetch_discharges(inst.npdes_permits, settings=settings) if inst.npdes_permits else []
        )

    land = None
    if boundary is not None and profile.federal_land_relpath is not None:
        delta, acreage_note = _acreage_reconciliation(
            boundary.acres, facts.base_area_acres, parts=boundary.parts
        )
        land = EnclaveLand(
            register_name=boundary.register_name,
            feature_name=boundary.feature_name,
            site_name=boundary.site_name,
            operational_status=boundary.status_label,
            is_joint_base=boundary.is_joint_base,
            register_acres=boundary.acres,
            parts=boundary.parts,
            record_acres=facts.base_area_acres,
            acreage_delta_pct=delta,
            acreage_note=acreage_note,
            relpath=profile.federal_land_relpath,
        )

    flows = [d.actual_average_flow_mgd for d in discharges if d.actual_average_flow_mgd is not None]
    scope_disagreement = (
        inst.tri_county_fips is not None and inst.tri_county_fips != profile.rsei_fips
    )
    scope_note = (
        f"The enclave reports TRI from {inst.tri_county_name} ({inst.tri_county_fips}); this "
        f"site's toxics backdrop covers {profile.county_name} ({profile.rsei_fips}). The county "
        f"inventory therefore does not contain the installation — it is out of scope by "
        f"construction, not missing. The row below is a second, one-facility reduction against "
        f"the enclave's own reporting county; the site's economic/RSEI unit is unchanged."
        if scope_disagreement
        else (
            f"The enclave reports TRI from the same county as this site's toxics backdrop "
            f"({profile.county_name}, {profile.rsei_fips}), so it already appears in the county "
            f"inventory; the row below is that same facility, isolated."
        )
    )

    citations = [c for c in (inst.record_citation, inst.register_citation) if c]
    citations += [c for c in (inst.pws_citation, inst.npdes_citation, inst.tri_citation) if c]

    return EnclaveProfile(
        meta={
            "subject": f"Federal enclave — {fac.name}",
            "registers": [
                "DoD MIRTA (site boundaries)",
                "EPA SDWIS (public water systems)",
                "EPA ECHO CWA (NPDES discharges)",
                "EPA RSEI/TRI (toxic releases)",
            ],
            "grounding_record": inst.record_relpath,
            "note": (
                "Documented figures are projected from the grounding record or carried verbatim "
                "from a named federal register. Nothing is estimated; an undisclosed figure is "
                "null ([open]), never defaulted."
            ),
        },
        slug=settings.site,
        name=fac.name,
        component=inst.component,
        agency=inst.agency,
        status=fac.status.value,
        record_relpath=inst.record_relpath,
        land=land,
        water=EnclaveWater(
            systems=systems,
            population_served=_sum_opt([s.population_served for s in systems]),
            service_connections=_sum_opt([s.service_connections for s in systems]),
            supply_wells=facts.supply_wells,
            well_fields=facts.well_fields,
            treatment_units=facts.air_stripping_units,
            aquifer=facts.aquifer,
            withdrawal_mgd=inst.withdrawal_mgd,
            withdrawal_citation=inst.withdrawal_citation,
        ),
        wastewater=EnclaveWastewater(
            discharges=discharges,
            reported_average_flow_mgd=round(sum(flows), 3) if flows else None,
        ),
        power=EnclavePower(load_mw=inst.load_mw, load_citation=inst.load_citation),
        toxics=EnclaveToxics(
            tri_facility_id=inst.tri_facility_id,
            tri_county_fips=inst.tri_county_fips,
            tri_county_name=inst.tri_county_name,
            epa_registry_id=inst.epa_registry_id,
            rsei=rsei_row,
            rsei_relpath=profile.enclave_rsei_relpath,
            site_rsei_fips=profile.rsei_fips,
            site_rsei_county_name=profile.county_name,
            scope_disagreement=scope_disagreement,
            scope_note=scope_note,
            npl_site_id=facts.epa_superfund_site_id,
            npl_listed_on=facts.npl_listing_date,
            npl_citation=facts.npl_citation,
            waste_disposal_sites=facts.waste_disposal_sites,
            disposal_period=facts.disposal_period,
            contaminants=list(facts.contaminants_vocs),
            statutory_authority=facts.statutory_authority,
        ),
        citations=citations,
    )


def write_enclave(profile: EnclaveProfile, path: Path) -> Path:
    """Write the enclave profile as deterministic YAML (no timestamp)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(
            profile.model_dump(mode="json", exclude_none=True),
            sort_keys=False,
            allow_unicode=True,
            width=100,
        ),
        encoding="utf-8",
    )
    return path


def regenerate(settings: Settings | None = None) -> dict[str, Path]:
    """Pull every federal register for the active site's enclave and write its committed set.

    Writes up to three artifacts and returns ``{name: path}`` for those written:
    ``federal-land.geojson`` (the MIRTA boundary), ``enclave.yaml`` (the assembled profile), and
    the enclave's one-facility RSEI reduction. A site with no enclave writes nothing.
    """
    settings = settings or get_settings()
    profile = active_profile(settings)
    inst = installation_of(profile)
    if inst is None:
        log.info("enclave.skip", site=settings.site, reason="no federal_installation facility")
        return {}

    written: dict[str, Path] = {}
    boundary = None
    if inst.register_name is not None:
        boundary = fetch_installation_boundary(
            inst.register_name, utm_epsg=profile.hydro_utm_epsg, settings=settings
        )
    if boundary is not None and profile.federal_land_relpath is not None:
        dest = settings.data_dir / profile.federal_land_relpath
        write_boundary(boundary_geojson(boundary, slug=settings.site), dest)
        written["federal-land"] = dest

    systems = fetch_water_systems(inst.pwsids, settings=settings) if inst.pwsids else []
    discharges = (
        fetch_discharges(inst.npdes_permits, settings=settings) if inst.npdes_permits else []
    )

    rsei_row: RseiFacility | None = None
    inv = build_enclave_rsei(settings)
    if inv is not None and profile.enclave_rsei_relpath is not None:
        dest = settings.data_dir / profile.enclave_rsei_relpath
        write_inventory(inv, dest.parent, filename=dest.name)
        written["enclave-rsei"] = dest
        rsei_row = inv.facilities[0] if inv.facilities else None

    assembled = build_enclave(
        settings,
        boundary=boundary,
        systems=systems,
        discharges=discharges,
        rsei_row=rsei_row,
    )
    if assembled is not None:
        written["enclave"] = write_enclave(assembled, enclave_path(settings))
    return written
