"""OHD000001 general-permit coverage + facility-own blowdown-discharge status (#1678).

The A2 harness half of the closed-loop cooling cycling epic (#1676). For each facility that
discloses a **recirculating / closed** cooling archetype (the claim the epic is testing), it
resolves two questions:

1. **OHD000001 coverage** — does the facility hold coverage under Ohio EPA's statewide data-center
   NPDES general permit (OHD000001)? Its low-volume-wastewater coverage (cooling-tower blowdown,
   boiler blowdown, air-compressor condensate) is the disclosure the cycling thesis predicts.
2. **Facility-own discharge** — is a facility-own NPDES / indirect-discharge permit on record at
   all, or does the record show none (→ genuinely dry, or blowing down to sewer under a City
   sewer-use agreement ECHO never sees → a C2 records request)?

Both answers are dominated by one ``[verified]`` gating fact, and as of **2026-07-21** that fact
changed shape: **OHD000001 was withdrawn** — Ohio EPA publicly declined to finalize it, saying the
individual NPDES process "is the most appropriate path forward" (it had been public-noticed
2025-10-31 with comment closing 2026-01-16). Every candidate still resolves to ``not_available``,
but the absence is now **permanent rather than pending**: no amount of waiting produces a coverage
list, and the only instrument that would ever disclose a data center's cooling discharge is an
individual NPDES permit. That is a materially stronger finding than the draft-gated one it
replaces — a general permit would have carried generic limits, whereas an individual permit is
public-noticed, fact-sheeted and individually limited. The lifecycle lives in one cited place
(:data:`OHD000001`); update it there and regenerate the coverage artifact. The per-facility
authorization check remains the forward-compatible seam in :func:`resolve_coverage`, now
unreachable for this permit and kept for the next general permit that does issue.

This module **produces the per-candidate record the A3 reconciliation reads**. It asserts no
per-site over-cycling conclusion — that is the per-site B-review (B1-B6). The absence of a
facility-own discharge permit under a "closed-loop-dry" claim is logged as an ``[open]`` gap
(→ C2 records request), never silently read as "confirmed dry".
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict

from watermark.config import Settings, get_settings
from watermark.logging import get_logger
from watermark.provenance import Confidence
from watermark.sites import SITES, CoolingModelType

log = get_logger(__name__)

OHD000001_ID = "OHD000001"
# Committed artifact relpath (under ``settings.data_dir``); regenerated by ``watermark oepa coverage``.
COVERAGE_RELPATH = "reference/oepa/ohd000001-coverage.yaml"

# The cooling archetypes that make a recirculating / closed cooling claim under review by epic
# #1676 — the mechanically-derived subset of the review cohort. A disclosed facility whose cooling
# method is UNKNOWN (e.g. Troy-Piqua, pending #1486) is deliberately NOT swept in here: it has no
# archetype claim to test yet and is handled in per-site B-review.
_CANDIDATE_ARCHETYPES: frozenset[CoolingModelType] = frozenset(
    {CoolingModelType.CLOSED_LOOP_DRY, CoolingModelType.HYBRID_ADIABATIC}
)


class GeneralPermitState(StrEnum):
    """The lifecycle state of a general permit — the gate on whether coverage is even possible."""

    DRAFT = "draft"  # public-noticed / in comment, but the Director has not issued it
    EFFECTIVE = "effective"  # issued and in force; facilities may obtain coverage
    WITHDRAWN = "withdrawn"  # the agency publicly declined to finalize it — it will never issue


class GeneralPermit(BaseModel):
    """A general NPDES permit's identity + lifecycle state (the coverage gate).

    Frozen: the module-level :data:`OHD000001` default is shared as a default argument across
    :func:`resolve_coverage`/:func:`resolve_cohort`, so it must not be mutable in place.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    permit_id: str
    title: str
    state: GeneralPermitState
    issued: str | None  # ISO date the draft was issued/public-noticed
    effective_date: str | None  # ISO date it took force (None while draft)
    comment_closed: str | None  # ISO date the comment period closed
    citation: str
    confidence: (
        Confidence  # strength of the lifecycle facts (high — from the permit's public notice)
    )
    asof: str  # ISO date this lifecycle state was last confirmed

    @property
    def effective(self) -> bool:
        """True only when the permit has actually issued (state effective AND an effective date)."""
        return self.state is GeneralPermitState.EFFECTIVE and self.effective_date is not None


# The OHD000001 lifecycle, cited. Draft as of ``asof``; this is the single place to update when the
# Director issues final action (flip ``state``/``effective_date``), then rerun ``watermark oepa
# coverage --write``. It is a documented fact about one statewide permit, not a per-site knob —
# so it lives as a cited named constant (the WS-23 pattern), not baked into a site profile.
OHD000001 = GeneralPermit(
    permit_id=OHD000001_ID,
    title="Ohio EPA Draft General NPDES Permit for Data Center Facilities",
    state=GeneralPermitState.WITHDRAWN,
    issued="2025-10-31",
    effective_date=None,
    comment_closed="2026-01-16",
    citation=(
        "Ohio EPA Division of Surface Water — draft General NPDES permit OHD000001 (public "
        "notice No. 215991; public hearing 2025-12-17); covered cooling water, low-volume "
        "wastewaters (cooling-tower/boiler blowdown, air-compressor condensate) and stormwater "
        "(data/catalog/reference/oepa-ohd000001-gp.yaml). WITHDRAWN: Ohio EPA Community Notice "
        "of 2026-07-21 states that after reviewing the comments it 'has decided not to move "
        "forward with finalizing the general permit' and that 'the individual NPDES permit "
        "issuance process is the most appropriate path forward at this time' "
        "(data/documents/oepa/2026-07-21-ohio-epa-will-not-finalize-data-center-general-permit"
        ".npdes-general-permits.html). The Director acted -- by declining -- so the coverage "
        "gate is now permanent rather than pending, and the replacement watch is whether an "
        "INDIVIDUAL NPDES application or draft permit appears for a given campus."
    ),
    confidence="high",  # the lifecycle facts are [verified] from the agency's own notices
    asof="2026-07-21",
)


class CoverageStatus(StrEnum):
    """Per-candidate OHD000001 coverage resolution."""

    COVERED = "covered"  # an OHD000001 authorization is on record for the facility
    NOT_SOUGHT = "not_sought"  # the permit is effective, but the facility filed no notice of intent
    NO_RECORD = "no_record"  # cannot be determined from the record
    NOT_AVAILABLE = "not_available"  # the permit is not yet effective — no facility can be covered


class FacilityOwnDischarge(StrEnum):
    """Whether a facility-own discharge permit is on record (independent of OHD000001)."""

    PRESENT = "present"  # a facility-own NPDES / indirect-discharge permit is on record
    ABSENT = "absent"  # searched and none found — a [verified] absence (→ to-sewer or dry)
    UNKNOWN = "unknown"  # not yet established — per-site B-review / C2 records request


class Candidate(BaseModel):
    """A closed-loop-claiming facility drawn from the site registry (the resolver's input)."""

    model_config = ConfigDict(extra="forbid")

    site: str
    facility: str
    cooling_claim: str  # the cooling archetype value, e.g. "closed_loop_dry"
    cooling_source: str  # SiteFacility.cooling_model_source (e.g. "reference" — an operator claim)
    cooling_citation: str
    # A facility-own NPDES / indirect-discharge permit id, when one is on record. None ⇒ not wired
    # yet (the epic's C2 records request establishes it); never fabricated to look complete.
    facility_npdes_id: str | None = None
    # A committed facility-own DMR extraction (relpath under data/extracted), when ingested.
    blowdown_dmr_relpath: str | None = None


class BlowdownCoverage(BaseModel):
    """Per-candidate resolution: OHD000001 coverage + facility-own discharge presence + the read."""

    model_config = ConfigDict(extra="forbid")

    site: str
    facility: str
    cooling_claim: str
    cooling_source: str
    ohd000001_status: CoverageStatus
    facility_own_discharge: FacilityOwnDischarge
    facility_npdes_id: str | None
    blowdown_dmr_relpath: str | None
    tag: str  # evidentiary tag on this resolution ("[verified]" for the draft-gated absence)
    # Strength of the coverage resolution, mapped from the tag (the ProvenancedValue convention),
    # so A3 can filter/sort structurally: high for the [verified] draft-gated absence, low for the
    # [open] effective-permit seam that still needs a per-facility authorization lookup.
    confidence: Confidence
    finding: str  # one-line evidentiary read
    citation: str


def closed_loop_candidates(*, settings: Settings | None = None) -> list[Candidate]:
    """Every registered facility disclosing a recirculating/closed cooling archetype (#1676 cohort).

    Iterates all ``SiteFacility`` on every registered ``SiteProfile`` (a site may disclose more than
    one campus) and keeps those whose ``cooling_model`` is in :data:`_CANDIDATE_ARCHETYPES`. Ordered
    by (site, facility) for a deterministic artifact.
    """
    settings = settings or get_settings()
    out: list[Candidate] = []
    for slug in sorted(SITES):
        profile = SITES[slug]
        for fac in profile.facilities:
            if fac.cooling_model not in _CANDIDATE_ARCHETYPES:
                continue
            out.append(
                Candidate(
                    site=slug,
                    facility=fac.name,
                    cooling_claim=fac.cooling_model.value,
                    cooling_source=fac.cooling_model_source,
                    cooling_citation=fac.cooling_model_citation,
                )
            )
    out.sort(key=lambda c: (c.site, c.facility))
    return out


def resolve_coverage(candidate: Candidate, *, gp: GeneralPermit = OHD000001) -> BlowdownCoverage:
    """Resolve one candidate's OHD000001 coverage + facility-own discharge status.

    The OHD000001 status is gated on the general permit's lifecycle. While it is draft (not
    effective), or once it has been **withdrawn**, no facility can be authorized, so the status is
    ``not_available`` — a ``[verified]`` cited absence. The two share a status but not a finding:
    a draft absence is *pending* and closes when the Director acts, a withdrawn one is *permanent*
    and can only be displaced by an individual NPDES permit. Had the permit instead issued,
    distinguishing ``covered`` from ``not_sought`` would need a per-facility authorization lookup
    that only exists then; that is the forward-compatible seam (the ``no_record``/``[open]``
    branch), never faked here.

    Facility-own discharge presence is ``present`` when a permit id is on record, else ``unknown``
    (the gap the C2 records request fills) — never ``absent`` unless a search has actually
    established the absence.
    """
    confidence: Confidence
    if gp.state is GeneralPermitState.WITHDRAWN:
        # The agency publicly declined to finalize it. Same gate as `draft` — no facility can be
        # authorized — but a categorically different finding: "never" rather than "not yet", so
        # the absence can no longer be closed by waiting, only by an individual NPDES appearing.
        status = CoverageStatus.NOT_AVAILABLE
        tag = "[verified]"
        confidence = "high"  # the withdrawal is a verified fact from the agency's own notice
        coverage_read = (
            f"{gp.permit_id} was WITHDRAWN (Ohio EPA declined to finalize it, {gp.asof}); it will "
            f"never issue, so {candidate.facility} can never hold blowdown coverage under it. "
            f"This absence is permanent, not pending: an INDIVIDUAL NPDES permit is now the only "
            f"instrument that would disclose this facility's cooling discharge."
        )
    elif not gp.effective:
        status = CoverageStatus.NOT_AVAILABLE
        tag = "[verified]"
        confidence = "high"  # the draft-gated absence is a verified fact about the permit
        coverage_read = (
            f"{gp.permit_id} is a draft general permit (not effective as of {gp.asof}); no "
            f"facility can be authorized under it, so {candidate.facility} cannot yet hold "
            f"blowdown coverage under it."
        )
    else:
        # The permit has issued: whether THIS facility filed a notice of intent is a per-facility
        # authorization lookup (ICIS/ECHO membership under the master general permit). Not wired
        # while the permit is draft — left as the seam rather than fabricating a covered/not-sought.
        status = CoverageStatus.NO_RECORD
        tag = "[open]"
        confidence = "low"  # unresolved seam pending a per-facility authorization lookup
        coverage_read = (
            f"{gp.permit_id} is effective (as of {gp.effective_date}); a per-facility "
            f"authorization lookup is needed to resolve whether {candidate.facility} sought "
            f"coverage — not yet wired."
        )

    if candidate.facility_npdes_id:
        own = FacilityOwnDischarge.PRESENT
        own_read = f"Facility-own discharge permit {candidate.facility_npdes_id} is on record" + (
            f" (DMR: {candidate.blowdown_dmr_relpath})." if candidate.blowdown_dmr_relpath else "."
        )
    else:
        own = FacilityOwnDischarge.UNKNOWN
        own_read = (
            "No facility-own discharge permit is wired — either genuinely dry, or blowdown goes to "
            "sewer under a City sewer-use agreement not in ECHO (→ C2 records request)."
        )

    return BlowdownCoverage(
        site=candidate.site,
        facility=candidate.facility,
        cooling_claim=candidate.cooling_claim,
        cooling_source=candidate.cooling_source,
        ohd000001_status=status,
        facility_own_discharge=own,
        facility_npdes_id=candidate.facility_npdes_id,
        blowdown_dmr_relpath=candidate.blowdown_dmr_relpath,
        tag=tag,
        confidence=confidence,
        finding=f"{coverage_read} {own_read}",
        citation=candidate.cooling_citation,
    )


def resolve_cohort(
    *, gp: GeneralPermit = OHD000001, settings: Settings | None = None
) -> tuple[GeneralPermit, list[BlowdownCoverage]]:
    """Resolve OHD000001 coverage for the whole closed-loop cohort (the artifact's payload)."""
    settings = settings or get_settings()
    coverages = [resolve_coverage(c, gp=gp) for c in closed_loop_candidates(settings=settings)]
    log.info(
        "blowdown.cohort_resolved",
        candidates=len(coverages),
        gp=gp.permit_id,
        gp_effective=gp.effective,
    )
    return gp, coverages


def coverage_document(gp: GeneralPermit, coverages: list[BlowdownCoverage]) -> dict[str, Any]:
    """A YAML-ready, deterministic document of the cohort's OHD000001 coverage resolution."""
    return {
        "meta": {
            "subject": (
                "Data-center blowdown discharge — OHD000001 general-permit coverage + "
                "facility-own DMR status (closed-loop cooling cycling epic #1676, A2)"
            ),
            "source": (
                "watermark.hydrology.blowdown — the site registry's closed-loop cohort x the "
                "OHD000001 permit lifecycle"
            ),
            "regenerate": "watermark oepa coverage --write",
            "asof": gp.asof,  # the coverage read is only as current as the permit-lifecycle refresh
            "discipline": (
                "OHD000001 coverage is gated on the permit lifecycle: while the general permit is "
                "draft (not effective), or once it has been withdrawn, no facility can be "
                "authorized, so the per-candidate status is not_available — a [verified] cited "
                "absence. Ohio EPA WITHDREW OHD000001 on 2026-07-21, so that absence is now "
                "permanent rather than pending, and an individual NPDES permit is the only "
                "instrument that would disclose a data center's cooling discharge. "
                "Facility-own discharge presence is "
                "unknown until a search establishes it (the C2 records request); an absence under a "
                "closed-loop-dry claim is a finding, never read as 'confirmed dry'. No per-site "
                "over-cycling conclusion is asserted here (that is the B-review)."
            ),
        },
        "general_permit": {
            "permit_id": gp.permit_id,
            "title": gp.title,
            "state": gp.state.value,
            "effective": gp.effective,
            "issued": gp.issued,
            "effective_date": gp.effective_date,
            "comment_closed": gp.comment_closed,
            "citation": gp.citation,
            "confidence": gp.confidence,
            "asof": gp.asof,
        },
        "candidates": [c.model_dump(mode="json") for c in coverages],
    }


def write_coverage(
    document: dict[str, Any], *, settings: Settings | None = None, out: Path | None = None
) -> Path:
    """Write the coverage document to ``reference/oepa/ohd000001-coverage.yaml`` (or ``out``)."""
    settings = settings or get_settings()
    path = out if out is not None else settings.data_dir / COVERAGE_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8"
    )
    return path
