"""Cooling-cycling reconciliation harness — claimed vs documented water account (#1679).

The A3 harness of the closed-loop cooling cycling epic (#1676). With the makeup side (A1
withdrawal connector, :mod:`watermark.hydrology.connectors.ohio_water_withdrawal`) and the
blowdown side (A2 discharge coverage, :mod:`watermark.hydrology.blowdown`) available, this
module assembles a **per-facility water account** and reconciles the operator's *claim*
against what records *document*:

1. Run the pinned ``SiteFacility.cooling_model`` archetype through
   :mod:`watermark.hydrology.cooling_models` to get the **predicted** makeup / consumptive /
   blowdown for the claim.
2. Read the **documented** makeup (A1) + blowdown (A2 DMR) where records exist.
3. Where both documented makeup *and* blowdown are on record, **back-solve cycles-of-
   concentration** (makeup / blowdown) — emitted as an ``[inference]`` bracket, never a
   headline scalar (the ratio of two self-reported figures is not a measurement).
4. Classify each facility into one of three outcomes (:class:`ReconcileOutcome`):

   * **discrepancy** — a low-water claim (``closed_loop_dry``) contradicted by documented
     flow ≫ the archetype's ~0 prediction (or over-cycling even vs a wet claim). Recommends
     re-archetyping up (``evaporative_tower`` / ``hybrid_adiabatic``, ``source="document"``).
   * **corroborated** — documented water is consistent with the claimed archetype. Two
     shapes: a dry claim with documented ≈ 0, and a wet claim (``evaporative_tower`` /
     ``hybrid_adiabatic``) whose documented water matches its prediction. Recommends the
     ``reference → document`` source upgrade.
   * **gap** — no documented makeup or blowdown to test against. Emits a records-request
     **lead payload** for C2 (#1688).

**The harness recommends; it does not mutate.** Re-archetyping a ``SiteFacility`` is a
reviewed B1-B6 edit landed with the instrument cited — this output is the evidence packet
for that edit, not an auto-applied change (the epic's evidentiary rule).

**The Intel positive control** (:data:`INTEL_CONTROL`) is the calibration baseline: an
openly-evaporative facility (exemplar New Albany / Intel, ~125 cooling towers) whose
documented water *equals its evaporative-tower prediction*. The harness must classify it
``corroborated`` — **not** a false ``discrepancy** just because it uses a lot of water. It
is a constructed calibration vector built into the harness, not a registered site (New
Albany carries no pinned ``SiteFacility`` — that is B6 #1686's work); its figures are
internally consistent with an evaporative tower at CoC ≈ 5, not documented Intel data.
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict

from watermark.config import Settings, get_settings
from watermark.hydrology import blowdown, cooling_models
from watermark.hydrology.model import CoolingBasis, ProvenancedValue
from watermark.logging import get_logger
from watermark.provenance import Confidence
from watermark.sites import SITES, CoolingModelType, SiteFacility

log = get_logger(__name__)

# Committed artifact relpath (under ``settings.data_dir``); regenerated by
# ``watermark cooling-reconcile --write``. Co-located with the A2 coverage artifact so the
# closed-loop epic's discharge-side references stay together.
RECONCILIATION_RELPATH = "reference/oepa/cooling-reconciliation.yaml"

# A documented flow at or below this (MGD) is read as ~0 — DMR rounding / trace non-cooling
# flow, not a cooling-water signal. It is the floor that separates a genuinely dry loop
# (documented ≈ 0) from a discrepancy (documented flow under a dry claim).
_MEANINGFUL_FLOW_MGD = 0.01

# The corroboration band: documented flow within [pred / TOL, pred x TOL] of the archetype's
# prediction corroborates it. Above the band (documented ≫ predicted) is a discrepancy even
# against a wet claim (over-cycling); below it, the claim is conservative vs the record — not
# the epic's under-reporting thesis, so it still corroborates (the record does not refute a
# lower-water reality). The band is wide because both sides are screening-grade figures.
_CORROBORATION_TOL = 2.0

# Fallback relative uncertainty on a back-solved CoC when neither documented input carries its
# own band — the ratio of two monthly-reported self-reported figures is not a point estimate.
_COC_REL_UNCERTAINTY = 0.15


class ReconcileOutcome(StrEnum):
    """The reconciliation of a facility's cooling claim against documented water."""

    DISCREPANCY = "discrepancy"  # low-water claim contradicted by documented flow
    CORROBORATED = "corroborated"  # documented water consistent with the claimed archetype
    GAP = "gap"  # no documented makeup/blowdown to test against → a C2 records request


class WaterAccount(BaseModel):
    """The assembled per-facility water account: predicted (claim) vs documented (record).

    ``predicted_*`` come from running the pinned archetype through
    :mod:`watermark.hydrology.cooling_models` — an ``[inference]`` from the claim. ``documented_*``
    are read from records (A1 makeup, A2 blowdown DMR) and are ``None`` until such a record
    exists. ``backsolved_cycles`` is present only when *both* documented makeup and blowdown are
    on record, and is always a bracket (never a scalar). Every figure carries its own provenance.
    """

    model_config = ConfigDict(extra="forbid")

    archetype: CoolingModelType
    it_load: ProvenancedValue  # MW
    predicted_makeup: ProvenancedValue  # MGD, the claim's cooling intake
    predicted_consumptive: ProvenancedValue  # MGD, the claim's evaporative loss
    predicted_blowdown: ProvenancedValue  # MGD, the claim's blowdown (makeup - evaporation)
    documented_makeup: ProvenancedValue | None = None  # MGD, A1 withdrawal record
    documented_blowdown: ProvenancedValue | None = None  # MGD, A2 discharge DMR
    disclosed_cycles: ProvenancedValue | None = None  # the operator's disclosed CoC, if any
    # The back-solved cycles-of-concentration (makeup / blowdown) — an [inference] BRACKET, never
    # a headline scalar. None unless both documented makeup and blowdown are on record.
    backsolved_cycles: ProvenancedValue | None = None
    # The A2 seasonality shape signal (warm/cool DMR-flow ratio) — a temperature-driven
    # evaporative blowdown peaks in summer (ratio ≫ 1), a dry loop is flat (~1). A shape
    # indicator, never a magnitude; None when no DMR flow series is on record.
    seasonality_warm_ratio: float | None = None


class ReconciliationRecord(BaseModel):
    """One facility's reconciliation: its water account, outcome, recommendation, provenance."""

    model_config = ConfigDict(extra="forbid")

    site: str
    facility: str
    # True for the Intel calibration control (a constructed positive control, not a registered
    # facility) — so consumers can filter it out of the live-cohort findings.
    is_control: bool = False
    claimed_archetype: str  # SiteFacility.cooling_model value under review
    claim_source: str  # SiteFacility.cooling_model_source (e.g. "reference" — an operator claim)
    claim_citation: str
    account: WaterAccount
    outcome: ReconcileOutcome
    # The harness RECOMMENDS (never mutates): for a discrepancy, the archetype to re-pin and
    # the source grade it would carry; for a corroboration, the source upgrade. None for a gap.
    recommended_archetype: str | None = None
    recommended_source: str | None = None
    # The C2 records-request lead payload (#1688) — present only for a gap outcome.
    lead: dict[str, Any] | None = None
    tag: str  # evidentiary tag on the reconciliation ("[open]" gap / "[inference]" / "[verified]")
    confidence: Confidence
    finding: str  # one-line evidentiary read


# --------------------------------------------------------------------- predicted water


def _predicted_basis(fac: SiteFacility, settings: Settings) -> CoolingBasis:
    """Run the facility's pinned archetype to get its predicted cooling-water basis.

    Dispatches through the archetype spec directly (not
    :func:`watermark.hydrology.cooling.derive_cooling_basis`, which reads the *active* site's
    facility) so a cross-site cohort facility is derived from its OWN disclosed inputs. The
    Lima IT-load fallback is guarded here exactly as ``derive_cooling_basis`` guards it: a
    non-``off`` archetype with no resolvable load would otherwise silently inherit Lima's
    275 MW basis.
    """
    model = fac.cooling_model
    if model is not CoolingModelType.OFF and fac.it_load_mw is None:
        raise ValueError(
            f"facility {fac.name!r} pins {model.value!r} but has no resolvable IT load — cannot "
            "predict its cooling-water account (only `off` is derivable without one)"
        )
    return cooling_models.get(model).derive(fac, cooling_models.CoolingParams(), settings)


def _predicted_blowdown(basis: CoolingBasis) -> ProvenancedValue:
    """Predicted blowdown (MGD) = makeup - evaporation for the claimed archetype.

    In a recirculating tower makeup = evaporation + blowdown, so blowdown = makeup -
    consumptive; a sealed dry loop predicts ~0 makeup → ~0 blowdown. Guards a tiny negative
    from rounding to 0. Bracketed (``unknown``) bases never reach here — the cohort is
    archetype-pinned.
    """
    makeup = basis.headline_makeup()
    consumptive = basis.headline_consumptive()
    assert makeup is not None and consumptive is not None  # cohort is never `unknown`/bracketed
    value = max(0.0, round(makeup.value - consumptive.value, 3))
    return ProvenancedValue.derived(
        value,
        "MGD",
        citation=(
            f"predicted blowdown = makeup {makeup.value:g} - evaporation {consumptive.value:g} "
            f"MGD for the {basis.cooling_model.value} archetype"
        ),
    )


# --------------------------------------------------------------------- back-solve


def _backsolve_cycles(
    documented_makeup: ProvenancedValue, documented_blowdown: ProvenancedValue
) -> ProvenancedValue | None:
    """Back-solve cycles-of-concentration = makeup / blowdown, as an ``[inference]`` bracket.

    Cycles-of-concentration is the makeup/blowdown ratio by definition. It is emitted as a
    bracket, never a headline scalar (the ratio of two self-reported monthly figures carries
    real uncertainty): the bracket comes from the inputs' own bands when present, else a
    ``±15%`` screening band. ``None`` when blowdown is ~0 (the ratio diverges — a non-physical
    input pair, not a cycling signal).
    """
    bd = documented_blowdown.value
    if bd <= _MEANINGFUL_FLOW_MGD:
        return None
    mk = documented_makeup.value
    point = round(mk / bd, 2)
    citation = (
        f"back-solved CoC = documented makeup {mk:g} MGD / documented blowdown {bd:g} MGD "
        "([inference]: the ratio of two self-reported figures, a bracket not a measurement)"
    )
    # Prefer the inputs' own bands (makeup_low/blowdown_high → CoC low, and vice-versa); fall
    # back to a relative screening band. Either way the result always carries a range.
    if documented_makeup.has_range or documented_blowdown.has_range:
        lo = round(documented_makeup.low_or_value / documented_blowdown.high_or_value, 2)
        hi = round(documented_makeup.high_or_value / documented_blowdown.low_or_value, 2)
        return ProvenancedValue.derived(
            point, "ratio", citation=citation, low=min(lo, point), high=max(hi, point)
        )
    return ProvenancedValue.derived(
        point, "ratio", citation=citation, rel_uncertainty=_COC_REL_UNCERTAINTY
    )


# --------------------------------------------------------------------- classify


def _classify(
    archetype: CoolingModelType,
    predicted_makeup: float,
    predicted_blowdown: float,
    documented_makeup: float | None,
    documented_blowdown: float | None,
) -> ReconcileOutcome:
    """Classify the claim↔document reconciliation into one of the three outcomes.

    The false-positive guard (the Intel control): a **discrepancy** requires the *claimed*
    archetype to predict little/no water — high documented water only contradicts a low-water
    claim. A wet claim (evaporative/hybrid) whose documents show matching high water is
    ``corroborated``, never flagged discrepant for using a lot of water.
    """
    if documented_makeup is None and documented_blowdown is None:
        return ReconcileOutcome.GAP
    # Prefer the blowdown signal (the A2 cooling-tower/low-volume-wastewater DMR — cooling-
    # specific). Fall back to makeup (A1 withdrawal) only when no blowdown is on record: a
    # documented withdrawal is TOTAL facility water (it may bundle domestic / humidification use),
    # so the makeup-only path is a weaker discrepancy signal that B-review must confirm against the
    # cooling-specific fraction — the harness screens, it does not adjudicate.
    if documented_blowdown is not None:
        documented, predicted = documented_blowdown, predicted_blowdown
    else:
        assert documented_makeup is not None
        documented, predicted = documented_makeup, predicted_makeup
    # A low-water claim (predicted ~0) with documented flow above the noise floor is the epic's
    # discrepancy — the dry claim is contradicted by the record.
    if predicted < _MEANINGFUL_FLOW_MGD:
        if documented >= _MEANINGFUL_FLOW_MGD:
            return ReconcileOutcome.DISCREPANCY
        return ReconcileOutcome.CORROBORATED  # both ~0 → corroborated dry
    # A wet claim: documented ≫ predicted is over-cycling (still a discrepancy); within or below
    # the band the record is consistent with (or more conservative than) the claim.
    if documented / predicted > _CORROBORATION_TOL:
        return ReconcileOutcome.DISCREPANCY
    return ReconcileOutcome.CORROBORATED


_WET_ARCHETYPES = frozenset({CoolingModelType.EVAPORATIVE_TOWER, CoolingModelType.HYBRID_ADIABATIC})


def _records_lead(site: str, fac: SiteFacility, claim_source: str) -> dict[str, Any]:
    """The C2 (#1688) records-request lead payload for a gap facility.

    A closed-loop claim with no documented makeup or blowdown is not "confirmed dry" — the
    blowdown may go to sewer under a City sewer-use / pretreatment agreement ECHO never sees.
    This is the structured ask that resolves it (R.C. 149.43), consumable by the C2 queue.
    """
    return {
        "kind": "records-request",
        "site": site,
        "facility": fac.name,
        "subject": "cooling-water account — makeup + blowdown records",
        "records_sought": [
            "industrial pretreatment / indirect-discharge (IU) permit",
            "sewer-use agreement + any cooling-tower blowdown authorization",
            "metered water-service use (makeup withdrawal)",
            "cooling-tower blowdown / low-volume-wastewater DMR",
        ],
        "holder": f"City / municipal water-sewer authority serving {site}",
        "rationale": (
            f"{fac.cooling_model.value} claim (source={claim_source}) with no facility-own "
            "discharge permit and no documented makeup — resolve whether blowdown goes to sewer "
            "under a City agreement not visible in ECHO/NPDES, or the loop is genuinely dry."
        ),
        "epic_ref": "#1688 (C2)",
        "tag": "[open]",
    }


def _finding(
    outcome: ReconcileOutcome,
    fac: SiteFacility,
    account: WaterAccount,
    claim_source: str,
) -> str:
    """A one-line evidentiary read for the reconciliation record."""
    arche = account.archetype.value
    if outcome is ReconcileOutcome.GAP:
        return (
            f"No documented makeup or blowdown for {fac.name}: the {arche} claim "
            f"(source={claim_source}) cannot yet be tested against records — an [open] gap, not "
            "'confirmed dry' (→ C2 records request #1688). Predicted makeup "
            f"{account.predicted_makeup.value:g} MGD."
        )
    if outcome is ReconcileOutcome.DISCREPANCY:
        doc = account.documented_blowdown or account.documented_makeup
        assert doc is not None
        season = (
            f" Seasonality warm/cool ratio {account.seasonality_warm_ratio:g} (a summer-peak "
            "shape corroborates temperature-driven evaporation)."
            if account.seasonality_warm_ratio is not None and account.seasonality_warm_ratio > 1.3
            else ""
        )
        return (
            f"Documented {doc.value:g} MGD {'blowdown' if account.documented_blowdown else 'makeup'} "
            f"contradicts the {arche} claim's ~{account.predicted_blowdown.value:g} MGD prediction — "
            f"re-archetype up with the instrument cited (B-review).{season}"
        )
    # corroborated
    if account.archetype in _WET_ARCHETYPES:
        doc = account.documented_blowdown or account.documented_makeup
        assert doc is not None
        coc = (
            f" Back-solved CoC {account.backsolved_cycles.value:g} "
            f"({account.backsolved_cycles.low_or_value:g}-{account.backsolved_cycles.high_or_value:g})."
            if account.backsolved_cycles is not None
            else ""
        )
        return (
            f"Documented {doc.value:g} MGD matches the {arche} claim's "
            f"{account.predicted_blowdown.value:g} MGD prediction — corroborated evaporative; "
            f"upgrade source {claim_source} → document.{coc}"
        )
    return (
        f"Documented water ≈ 0 corroborates the {arche} dry claim — upgrade source "
        f"{claim_source} → document."
    )


def reconcile_facility(
    fac: SiteFacility,
    *,
    site: str,
    claim_source: str,
    claim_citation: str,
    settings: Settings,
    documented_makeup: ProvenancedValue | None = None,
    documented_blowdown: ProvenancedValue | None = None,
    seasonality_warm_ratio: float | None = None,
    is_control: bool = False,
) -> ReconciliationRecord:
    """Reconcile one facility's cooling claim against its documented water account.

    Pure over its inputs: the predicted account comes from the pinned archetype (under
    ``settings`` — pass the facility's OWN site settings so a hybrid assist window reads its
    climatology, not the active site's), and the documented figures are injected (the cohort
    resolver reads them from A1/A2). Emits the outcome, a recommendation, and — for a gap — a
    C2 lead payload. Recommends only; it never mutates ``fac.cooling_model``.
    """
    basis = _predicted_basis(fac, settings)
    predicted_makeup = basis.headline_makeup()
    predicted_consumptive = basis.headline_consumptive()
    assert predicted_makeup is not None and predicted_consumptive is not None
    predicted_blowdown = _predicted_blowdown(basis)

    # A disclosed/stated CoC is reference-grade, not a self-verified measurement — `cooling_models`
    # itself carries cycles as an assumption. `from_reference` keeps it honest (and the Intel
    # control's is a constructed calibration value, never a document about a real facility).
    disclosed_cycles = (
        ProvenancedValue.from_reference(
            fac.cycles_of_concentration,
            "ratio",
            citation=fac.cycles_citation or "disclosed cycles of concentration",
        )
        if fac.cycles_of_concentration is not None
        else None
    )
    backsolved_cycles = (
        _backsolve_cycles(documented_makeup, documented_blowdown)
        if documented_makeup is not None and documented_blowdown is not None
        else None
    )

    account = WaterAccount(
        archetype=fac.cooling_model,
        it_load=basis.it_load,
        predicted_makeup=predicted_makeup,
        predicted_consumptive=predicted_consumptive,
        predicted_blowdown=predicted_blowdown,
        documented_makeup=documented_makeup,
        documented_blowdown=documented_blowdown,
        disclosed_cycles=disclosed_cycles,
        backsolved_cycles=backsolved_cycles,
        seasonality_warm_ratio=seasonality_warm_ratio,
    )

    outcome = _classify(
        fac.cooling_model,
        predicted_makeup.value,
        predicted_blowdown.value,
        documented_makeup.value if documented_makeup is not None else None,
        documented_blowdown.value if documented_blowdown is not None else None,
    )

    recommended_archetype: str | None = None
    recommended_source: str | None = None
    lead: dict[str, Any] | None = None
    if outcome is ReconcileOutcome.DISCREPANCY:
        # Re-archetype up: a summer-peak seasonality points at a continuously-evaporative tower;
        # otherwise recommend the evaporative upper bound and let B-review pin tower vs hybrid
        # with the instrument cited.
        recommended_archetype = CoolingModelType.EVAPORATIVE_TOWER.value
        recommended_source = "document"
        tag = "[verified]"  # a documented discharge is a [verified] record about the facility
        confidence: Confidence = "high"
    elif outcome is ReconcileOutcome.CORROBORATED:
        recommended_archetype = fac.cooling_model.value  # unchanged; the claim holds
        recommended_source = "document"
        tag = "[verified]"
        confidence = "high"
    else:  # GAP
        lead = _records_lead(site, fac, claim_source)
        tag = "[open]"
        confidence = "low"

    return ReconciliationRecord(
        site=site,
        facility=fac.name,
        is_control=is_control,
        claimed_archetype=fac.cooling_model.value,
        claim_source=claim_source,
        claim_citation=claim_citation,
        account=account,
        outcome=outcome,
        recommended_archetype=recommended_archetype,
        recommended_source=recommended_source,
        lead=lead,
        tag=tag,
        confidence=confidence,
        finding=_finding(outcome, fac, account, claim_source),
    )


# --------------------------------------------------------------------- the Intel control

# The openly-evaporative positive control (exemplar: Intel "Ohio One" / New Albany, ~125
# cooling towers). NOT a registered site — New Albany carries no pinned SiteFacility (that is
# B6 #1686's work); this is a constructed calibration vector built into the harness, internally
# consistent with an evaporative tower at CoC ≈ 5. The harness must classify it CORROBORATED
# (documented water matches the evaporative prediction), never a false DISCREPANCY. Its
# documented figures are a calibration vector, NOT documented Intel data.
_INTEL_CITE = (
    "constructed calibration control (exemplar: Intel 'Ohio One' / New Albany, openly "
    "evaporative, ~125 cooling towers) — figures internally consistent with an evaporative "
    "tower at CoC≈5, NOT documented Intel data; New Albany carries no pinned SiteFacility "
    "(B6 #1686). The harness must classify it corroborated-evaporative (no false discrepancy)."
)
INTEL_CONTROL_FACILITY = SiteFacility(
    name="Intel evaporative control (New Albany)",
    status="confirmed",  # a disclosed facility is at least confirmed
    it_load_mw=150.0,
    it_load_low_mw=120.0,
    it_load_high_mw=180.0,
    it_load_citation=_INTEL_CITE,
    it_load_source="reference",
    cooling_model=CoolingModelType.EVAPORATIVE_TOWER,
    cooling_model_source="reference",
    cooling_model_citation=_INTEL_CITE,
    wue_l_per_kwh=1.8,
    wue_citation=_INTEL_CITE,
    cycles_of_concentration=5.0,
    cycles_citation=_INTEL_CITE,
)
# Documented water for the control: an evaporative facility at ~150 MW / WUE 1.8 / CoC 5
# predicts ~2.14 MGD makeup and ~0.43 MGD blowdown; these documented figures land just above
# that (ratio ~1.05) — inside the corroboration band, back-solving CoC ≈ 4.9 (≈ the disclosed
# 5). The harness must corroborate, not flag over-cycling.
INTEL_DOCUMENTED_MAKEUP = ProvenancedValue.from_reference(2.2, "MGD", citation=_INTEL_CITE)
INTEL_DOCUMENTED_BLOWDOWN = ProvenancedValue.from_reference(0.45, "MGD", citation=_INTEL_CITE)
INTEL_SEASONALITY_WARM_RATIO = 1.6  # a temperature-driven summer peak — the evaporative shape


def intel_control(*, settings: Settings | None = None) -> ReconciliationRecord:
    """The Intel positive control, reconciled — the harness's calibration self-check.

    Evaporative_tower needs no climatology, so any settings resolves it; a fresh
    ``Settings()`` is used when none is passed so the control is standalone-runnable.
    """
    settings = settings or Settings()
    return reconcile_facility(
        INTEL_CONTROL_FACILITY,
        site="new-albany",
        claim_source=INTEL_CONTROL_FACILITY.cooling_model_source,
        claim_citation=_INTEL_CITE,
        settings=settings,
        documented_makeup=INTEL_DOCUMENTED_MAKEUP,
        documented_blowdown=INTEL_DOCUMENTED_BLOWDOWN,
        seasonality_warm_ratio=INTEL_SEASONALITY_WARM_RATIO,
        is_control=True,
    )


# --------------------------------------------------------------------- documented-water read


def _site_settings(slug: str, base: Settings) -> Settings:
    """Fresh per-site ``Settings`` carrying the base run's offline flags.

    A fresh ``Settings(site=...)`` re-runs the profile-knob fill (so a hybrid facility's assist
    window reads its OWN site's climatology), which ``model_copy`` would skip. The offline
    knobs are propagated so a cohort run stays hermetic in tests / ``--offline``.
    """
    overrides: dict[str, Any] = {"site": slug}
    if base.hydro_offline:
        overrides["hydro_offline"] = True
    if base.hydro_fixtures_dir is not None:
        overrides["hydro_fixtures_dir"] = base.hydro_fixtures_dir
    return Settings(**overrides)


def _documented_water(
    candidate: blowdown.Candidate, settings: Settings
) -> tuple[ProvenancedValue | None, ProvenancedValue | None, float | None]:
    """Best-effort documented makeup / blowdown / seasonality for a cohort candidate.

    Wires the A1 + A2 seams; returns ``(None, None, None)`` for every live candidate today —
    the honest current state, which is itself the gap finding:

    * **Blowdown (A2)** comes from :func:`watermark.hydrology.blowdown.resolve_coverage`. While
      OHD000001 is a draft permit and no facility-own DMR is on record, it is ``unknown`` → no
      documented blowdown. When a DMR relpath lands, this reads it.
    * **Makeup (A1)** would come from the Ohio DNR WWFRP registry, but that connector has only
      built Allen County and none of the closed-loop candidates report withdrawal there — so
      there is no documented makeup to read. The seam is left for a peer-county registry.

    The seams auto-activate when the records land; nothing is fabricated to look complete.
    """
    coverage = blowdown.resolve_coverage(candidate)
    documented_blowdown: ProvenancedValue | None = None
    seasonality_warm_ratio: float | None = None
    if (
        coverage.facility_own_discharge is blowdown.FacilityOwnDischarge.PRESENT
        and candidate.blowdown_dmr_relpath is not None
    ):
        # A facility-own DMR is on record — the forward seam. No live candidate reaches here yet;
        # reading the DMR flow magnitude + seasonality is left to the B-review that lands it, so
        # a value is never fabricated from an absent record.
        log.info(
            "cooling_reconcile.dmr_seam",
            site=candidate.site,
            facility=candidate.facility,
            relpath=candidate.blowdown_dmr_relpath,
        )
    return None, documented_blowdown, seasonality_warm_ratio


# --------------------------------------------------------------------- cohort


def reconcile_cohort(*, settings: Settings | None = None) -> list[ReconciliationRecord]:
    """Reconcile every closed-loop cohort facility + the Intel positive control.

    The cohort is A2's registry-derived closed-loop set (:func:`blowdown.closed_loop_candidates`
    — every ``SiteFacility`` pinning ``closed_loop_dry`` / ``hybrid_adiabatic``). Each facility
    is derived under its OWN site's settings so a cross-site cohort never leaks the active site's
    climatology. The Intel control is appended and reconciled the same way. Ordered by
    (is_control, site, facility) so the control sorts last after the live findings.
    """
    settings = settings or get_settings()
    records: list[ReconciliationRecord] = []
    for candidate in blowdown.closed_loop_candidates(settings=settings):
        profile = SITES[candidate.site]
        fac = next((f for f in profile.facilities if f.name == candidate.facility), None)
        if fac is None:  # pragma: no cover - the candidate list is built from these facilities
            continue
        makeup, blowdown_pv, warm_ratio = _documented_water(candidate, settings)
        records.append(
            reconcile_facility(
                fac,
                site=candidate.site,
                claim_source=candidate.cooling_source,
                claim_citation=candidate.cooling_citation,
                settings=_site_settings(candidate.site, settings),
                documented_makeup=makeup,
                documented_blowdown=blowdown_pv,
                seasonality_warm_ratio=warm_ratio,
            )
        )
    records.append(intel_control(settings=settings))
    records.sort(key=lambda r: (r.is_control, r.site, r.facility))
    log.info(
        "cooling_reconcile.cohort_resolved",
        facilities=len(records),
        outcomes={o.value: sum(1 for r in records if r.outcome is o) for o in ReconcileOutcome},
    )
    return records


# --------------------------------------------------------------------- artifact


def reconciliation_document(records: list[ReconciliationRecord]) -> dict[str, Any]:
    """A YAML-ready, deterministic document of the cohort's cooling reconciliation."""
    counts = {o.value: sum(1 for r in records if r.outcome is o) for o in ReconcileOutcome}
    return {
        "meta": {
            "subject": (
                "Data-center cooling-cycling reconciliation — claimed cooling archetype vs the "
                "documented water account (closed-loop cooling cycling epic #1676, A3 #1679)"
            ),
            "source": (
                "watermark.hydrology.cooling_reconcile — the A2 closed-loop cohort x the "
                "archetype-predicted water account (cooling_models) x documented makeup (A1) / "
                "blowdown (A2), plus the Intel evaporative positive control"
            ),
            "regenerate": "watermark cooling-reconcile --write",
            # As current as the A2 permit-lifecycle refresh the documented-blowdown read gates on.
            "asof": blowdown.OHD000001.asof,
            "outcomes": counts,
            "discipline": (
                "The harness RECOMMENDS; it never mutates cooling_model — re-archetyping is a "
                "reviewed B1-B6 edit with the instrument cited. A back-solved cycles-of-"
                "concentration is an [inference] bracket, never a headline scalar. A gap (no "
                "documented makeup/blowdown) is an [open] records-request lead for C2 (#1688), "
                "never read as 'confirmed dry'. The Intel row is a constructed positive control "
                "(openly evaporative) the harness must classify corroborated, not a false "
                "discrepancy — it is a calibration vector, not documented Intel data."
            ),
        },
        "candidates": [r.model_dump(mode="json") for r in records],
    }


def write_reconciliation(
    document: dict[str, Any], *, settings: Settings | None = None, out: Path | None = None
) -> Path:
    """Write the reconciliation document to ``reference/oepa/cooling-reconciliation.yaml``."""
    settings = settings or get_settings()
    path = out if out is not None else settings.data_dir / RECONCILIATION_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8"
    )
    return path
