"""AERMET input emitter — surface + upper-air met → AERMET-ready files.

Composes the ISD surface (:mod:`.isd`) and IGRA upper-air (:mod:`.igra`) pulls into the file
set AERMET's Stage-1 extraction reads: the raw ISHD surface file, the raw IGRA upper-air
file, and a control runstream (``aermet.inp``) wiring them through the data-driven stages
(UPPERAIR / SURFACE extract + QA → MERGE).

**No fabricated meteorology.** The runstream stops at MERGE; the METPREP surface-
characteristics inputs (albedo, Bowen ratio, roughness by sector/season) are site land-use
values the modeller supplies — emitted only as a commented template, never invented. The
final ``.SFC``/``.PFL`` files are produced by the AERMET **binary** (#1178) from these
inputs; this emitter stages that run, it does not run it.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, ConfigDict

from watermark.air.connectors.igra import SoundingSeries
from watermark.air.connectors.isd import SurfaceSeries


class AermetInputs(BaseModel):
    """The staged AERMET input file set + the provenance/QA to run it."""

    model_config = ConfigDict(extra="forbid")

    site_label: str
    surface_station: str
    upperair_station: str
    year: int
    start_date: str | None  # YYYY-MM-DD
    end_date: str | None
    utc_offset: int  # AERMET GMT field: hours added to local standard time to obtain UTC
    surface_coverage_fraction: float
    n_soundings: int
    surface_path: str
    upperair_path: str
    runstream_path: str


def _date_range(times: list[str]) -> tuple[str | None, str | None]:
    dates = sorted({t[:10] for t in times})
    return (dates[0], dates[-1]) if dates else (None, None)


def _nominal_utc_offset(longitude: float | None) -> int:
    """Solar-nominal UTC offset (hours) from longitude — flagged 'verify' in the runstream."""
    return round(-longitude / 15.0) if longitude is not None else 0


def _xdates(start: str | None, end: str | None) -> str:
    if start is None or end is None:
        return "**   XDATES  <set the extraction date range>"
    return f"   XDATES  {start.replace('-', '/')}  TO  {end.replace('-', '/')}"


def write_aermet_inputs(
    surface: SurfaceSeries,
    upperair: SoundingSeries,
    *,
    out_dir: Path,
    site_label: str,
    utc_offset: int | None = None,
) -> AermetInputs:
    """Write the ISHD surface file, IGRA upper-air file, and the AERMET runstream.

    ``utc_offset`` is AERMET's GMT field (hours added to local standard time to get UTC); when
    omitted it defaults to a solar-nominal value derived from the station longitude and is
    flagged in the runstream for the modeller to verify against the station's civil time zone.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    offset = _nominal_utc_offset(surface.longitude) if utc_offset is None else utc_offset

    sfc_path = out_dir / f"{surface.station_id}.ishd"
    ua_path = out_dir / f"{upperair.station_id}.igra"
    inp_path = out_dir / "aermet.inp"
    sfc_path.write_text(surface.raw_ishd, encoding="latin-1")
    ua_path.write_text(upperair.raw_igra, encoding="latin-1")

    start, end = _date_range([o.time for o in surface.observations])
    ua_start, ua_end = _date_range([s.time for s in upperair.soundings])
    runstream = _runstream(
        surface=surface,
        upperair=upperair,
        sfc_name=sfc_path.name,
        ua_name=ua_path.name,
        site_label=site_label,
        offset=offset,
        sfc_dates=(start, end),
        ua_dates=(ua_start, ua_end),
    )
    inp_path.write_text(runstream, encoding="ascii")

    return AermetInputs(
        site_label=site_label,
        surface_station=surface.station_id,
        upperair_station=upperair.station_id,
        year=surface.year,
        start_date=start,
        end_date=end,
        utc_offset=offset,
        surface_coverage_fraction=surface.coverage_fraction(),
        n_soundings=len(upperair.soundings),
        surface_path=str(sfc_path),
        upperair_path=str(ua_path),
        runstream_path=str(inp_path),
    )


def _loc(sid: str, lon: float | None, lat: float | None, offset: int, elev: float | None) -> str:
    lon_s = f"{lon:.4f}" if lon is not None else "<lon>"
    lat_s = f"{lat:.4f}" if lat is not None else "<lat>"
    tail = f"  {elev:.1f}" if elev is not None else ""
    return f"   LOCATION  {sid}  {lon_s}  {lat_s}  {offset}{tail}"


def _runstream(
    *,
    surface: SurfaceSeries,
    upperair: SoundingSeries,
    sfc_name: str,
    ua_name: str,
    site_label: str,
    offset: int,
    sfc_dates: tuple[str | None, str | None],
    ua_dates: tuple[str | None, str | None],
) -> str:
    """Assemble the AERMET Stage-1 → MERGE control file (data-driven stages only)."""
    lines = [
        "** AERMET control file - generated by `watermark aermet` (#1179)",
        f"** Site: {site_label}   Year: {surface.year}",
        f"** Surface (ISHD): {surface.station_id}   Upper air (IGRA): {upperair.station_id}",
        "** LOCATION longitude is west-negative (AERMET >=19191); the trailing integer is the",
        "** GMT offset (hours added to local standard time to obtain UTC) - VERIFY per site.",
        "**",
        "JOB",
        "   REPORT    aermet_report.txt",
        "   MESSAGES  aermet_messages.txt",
        "",
        "UPPERAIR",
        f"   DATA      {ua_name}  IGRA",
        "   EXTRACT   upperair.extract",
        "   QAOUT     upperair.qaout",
        _xdates(*ua_dates),
        _loc(upperair.station_id, upperair.longitude, upperair.latitude, offset, None),
        "",
        "SURFACE",
        f"   DATA      {sfc_name}  ISHD",
        "   EXTRACT   surface.extract",
        "   QAOUT     surface.qaout",
        _xdates(*sfc_dates),
        _loc(surface.station_id, surface.longitude, surface.latitude, offset, surface.elevation_m),
        "",
        "MERGE",
        "   SURFDATA  surface.qaout",
        "   UADATA    upperair.qaout",
        "   OUTPUT    merge.out",
        _xdates(*sfc_dates),
        "",
        "** ---------------------------------------------------------------------------",
        "** METPREP (SFC/PFL generation) needs site-specific surface characteristics -",
        "** albedo, Bowen ratio, and roughness by sector/season from the site's land use.",
        "** These are the modeller's inputs (#1178 engine + #1180 site facility land use);",
        "** they are NOT emitted here to avoid fabricating meteorology. Template:",
        "** METPREP",
        "**    DATA      merge.out",
        "**    FREQ_SECT  ANNUAL  <n_sectors>",
        "**    SECTOR     1  <start_deg>  <end_deg>",
        "**    SITE_CHAR  1  1  <albedo>  <bowen>  <roughness>   ** per sector/season",
        "**    OUTPUT     " + f"{site_label}.sfc",
        "**    PROFILE    " + f"{site_label}.pfl",
        "",
    ]
    return "\n".join(lines)
